// Словарь Кеду — HSK 1-2, сгруппировано по темам/урокам.
// Формат: { id, hanzi, pinyin, ru, lesson }
// Массив легко расширяется до тысяч слов — просто добавляй объекты с новым lesson.

const LESSONS = [
  { id: 1, title: "Приветствия", icon: "👋" },
  { id: 2, title: "Местоимения", icon: "🙋" },
  { id: 3, title: "Числа", icon: "🔢" },
  { id: 4, title: "Семья", icon: "👪" },
  { id: 5, title: "Еда и напитки", icon: "🍜" },
  { id: 6, title: "Время", icon: "⏰" },
  { id: 7, title: "Цвета", icon: "🎨" },
  { id: 8, title: "Действия", icon: "🏃" },
  { id: 9, title: "Место", icon: "📍" },
  { id: 10, title: "Погода", icon: "☀️" },
  { id: 11, title: "Тело", icon: "🖐️" },
  { id: 12, title: "Одежда", icon: "👕" },
  { id: 13, title: "Животные", icon: "🐱" },
  { id: 14, title: "Профессии", icon: "💼" },
  { id: 15, title: "Качества", icon: "✨" },
  { id: 16, title: "Вопросы", icon: "❓" },
];

const WORDS = [
  // 1. Приветствия
  { hanzi: "你好", pinyin: "nǐ hǎo", ru: "привет", lesson: 1 },
  { hanzi: "谢谢", pinyin: "xièxie", ru: "спасибо", lesson: 1 },
  { hanzi: "不客气", pinyin: "bú kèqi", ru: "не за что", lesson: 1 },
  { hanzi: "再见", pinyin: "zàijiàn", ru: "до свидания", lesson: 1 },
  { hanzi: "对不起", pinyin: "duìbuqǐ", ru: "извините", lesson: 1 },
  { hanzi: "没关系", pinyin: "méi guānxi", ru: "ничего страшного", lesson: 1 },
  { hanzi: "请", pinyin: "qǐng", ru: "пожалуйста (просьба)", lesson: 1 },
  { hanzi: "是", pinyin: "shì", ru: "быть / да", lesson: 1 },
  { hanzi: "不", pinyin: "bù", ru: "не", lesson: 1 },
  { hanzi: "好", pinyin: "hǎo", ru: "хорошо", lesson: 1 },

  // 2. Местоимения
  { hanzi: "我", pinyin: "wǒ", ru: "я", lesson: 2 },
  { hanzi: "你", pinyin: "nǐ", ru: "ты", lesson: 2 },
  { hanzi: "他", pinyin: "tā", ru: "он", lesson: 2 },
  { hanzi: "她", pinyin: "tā", ru: "она", lesson: 2 },
  { hanzi: "我们", pinyin: "wǒmen", ru: "мы", lesson: 2 },
  { hanzi: "你们", pinyin: "nǐmen", ru: "вы", lesson: 2 },
  { hanzi: "他们", pinyin: "tāmen", ru: "они", lesson: 2 },
  { hanzi: "这", pinyin: "zhè", ru: "это", lesson: 2 },
  { hanzi: "那", pinyin: "nà", ru: "то", lesson: 2 },
  { hanzi: "谁", pinyin: "shéi", ru: "кто", lesson: 2 },

  // 3. Числа
  { hanzi: "一", pinyin: "yī", ru: "один", lesson: 3 },
  { hanzi: "二", pinyin: "èr", ru: "два", lesson: 3 },
  { hanzi: "三", pinyin: "sān", ru: "три", lesson: 3 },
  { hanzi: "四", pinyin: "sì", ru: "четыре", lesson: 3 },
  { hanzi: "五", pinyin: "wǔ", ru: "пять", lesson: 3 },
  { hanzi: "六", pinyin: "liù", ru: "шесть", lesson: 3 },
  { hanzi: "七", pinyin: "qī", ru: "семь", lesson: 3 },
  { hanzi: "八", pinyin: "bā", ru: "восемь", lesson: 3 },
  { hanzi: "九", pinyin: "jiǔ", ru: "девять", lesson: 3 },
  { hanzi: "十", pinyin: "shí", ru: "десять", lesson: 3 },
  { hanzi: "百", pinyin: "bǎi", ru: "сто", lesson: 3 },
  { hanzi: "零", pinyin: "líng", ru: "ноль", lesson: 3 },

  // 4. Семья
  { hanzi: "爸爸", pinyin: "bàba", ru: "папа", lesson: 4 },
  { hanzi: "妈妈", pinyin: "māma", ru: "мама", lesson: 4 },
  { hanzi: "哥哥", pinyin: "gēge", ru: "старший брат", lesson: 4 },
  { hanzi: "弟弟", pinyin: "dìdi", ru: "младший брат", lesson: 4 },
  { hanzi: "姐姐", pinyin: "jiějie", ru: "старшая сестра", lesson: 4 },
  { hanzi: "妹妹", pinyin: "mèimei", ru: "младшая сестра", lesson: 4 },
  { hanzi: "儿子", pinyin: "érzi", ru: "сын", lesson: 4 },
  { hanzi: "女儿", pinyin: "nǚ'ér", ru: "дочь", lesson: 4 },
  { hanzi: "朋友", pinyin: "péngyou", ru: "друг", lesson: 4 },
  { hanzi: "家", pinyin: "jiā", ru: "дом / семья", lesson: 4 },

  // 5. Еда и напитки
  { hanzi: "吃", pinyin: "chī", ru: "есть (кушать)", lesson: 5 },
  { hanzi: "喝", pinyin: "hē", ru: "пить", lesson: 5 },
  { hanzi: "米饭", pinyin: "mǐfàn", ru: "рис (варёный)", lesson: 5 },
  { hanzi: "面条", pinyin: "miàntiáo", ru: "лапша", lesson: 5 },
  { hanzi: "水", pinyin: "shuǐ", ru: "вода", lesson: 5 },
  { hanzi: "茶", pinyin: "chá", ru: "чай", lesson: 5 },
  { hanzi: "咖啡", pinyin: "kāfēi", ru: "кофе", lesson: 5 },
  { hanzi: "牛奶", pinyin: "niúnǎi", ru: "молоко", lesson: 5 },
  { hanzi: "鸡蛋", pinyin: "jīdàn", ru: "яйцо", lesson: 5 },
  { hanzi: "苹果", pinyin: "píngguǒ", ru: "яблоко", lesson: 5 },
  { hanzi: "菜", pinyin: "cài", ru: "блюдо / овощи", lesson: 5 },
  { hanzi: "水果", pinyin: "shuǐguǒ", ru: "фрукты", lesson: 5 },

  // 6. Время
  { hanzi: "今天", pinyin: "jīntiān", ru: "сегодня", lesson: 6 },
  { hanzi: "明天", pinyin: "míngtiān", ru: "завтра", lesson: 6 },
  { hanzi: "昨天", pinyin: "zuótiān", ru: "вчера", lesson: 6 },
  { hanzi: "现在", pinyin: "xiànzài", ru: "сейчас", lesson: 6 },
  { hanzi: "年", pinyin: "nián", ru: "год", lesson: 6 },
  { hanzi: "月", pinyin: "yuè", ru: "месяц", lesson: 6 },
  { hanzi: "号", pinyin: "hào", ru: "число (дата)", lesson: 6 },
  { hanzi: "星期", pinyin: "xīngqī", ru: "неделя", lesson: 6 },
  { hanzi: "点", pinyin: "diǎn", ru: "час", lesson: 6 },
  { hanzi: "分钟", pinyin: "fēnzhōng", ru: "минута", lesson: 6 },
  { hanzi: "早上", pinyin: "zǎoshang", ru: "утро", lesson: 6 },
  { hanzi: "晚上", pinyin: "wǎnshang", ru: "вечер", lesson: 6 },

  // 7. Цвета
  { hanzi: "红色", pinyin: "hóngsè", ru: "красный", lesson: 7 },
  { hanzi: "黄色", pinyin: "huángsè", ru: "жёлтый", lesson: 7 },
  { hanzi: "蓝色", pinyin: "lánsè", ru: "синий", lesson: 7 },
  { hanzi: "绿色", pinyin: "lǜsè", ru: "зелёный", lesson: 7 },
  { hanzi: "黑色", pinyin: "hēisè", ru: "чёрный", lesson: 7 },
  { hanzi: "白色", pinyin: "báisè", ru: "белый", lesson: 7 },
  { hanzi: "颜色", pinyin: "yánsè", ru: "цвет", lesson: 7 },

  // 8. Действия
  { hanzi: "去", pinyin: "qù", ru: "идти / ехать", lesson: 8 },
  { hanzi: "来", pinyin: "lái", ru: "приходить", lesson: 8 },
  { hanzi: "看", pinyin: "kàn", ru: "смотреть / читать", lesson: 8 },
  { hanzi: "听", pinyin: "tīng", ru: "слушать", lesson: 8 },
  { hanzi: "说", pinyin: "shuō", ru: "говорить", lesson: 8 },
  { hanzi: "写", pinyin: "xiě", ru: "писать", lesson: 8 },
  { hanzi: "读", pinyin: "dú", ru: "читать вслух", lesson: 8 },
  { hanzi: "买", pinyin: "mǎi", ru: "покупать", lesson: 8 },
  { hanzi: "做", pinyin: "zuò", ru: "делать", lesson: 8 },
  { hanzi: "学习", pinyin: "xuéxí", ru: "учиться", lesson: 8 },
  { hanzi: "工作", pinyin: "gōngzuò", ru: "работать", lesson: 8 },
  { hanzi: "睡觉", pinyin: "shuìjiào", ru: "спать", lesson: 8 },
  { hanzi: "喜欢", pinyin: "xǐhuan", ru: "нравиться", lesson: 8 },

  // 9. Место
  { hanzi: "学校", pinyin: "xuéxiào", ru: "школа", lesson: 9 },
  { hanzi: "医院", pinyin: "yīyuàn", ru: "больница", lesson: 9 },
  { hanzi: "商店", pinyin: "shāngdiàn", ru: "магазин", lesson: 9 },
  { hanzi: "餐厅", pinyin: "cāntīng", ru: "ресторан", lesson: 9 },
  { hanzi: "公司", pinyin: "gōngsī", ru: "компания / офис", lesson: 9 },
  { hanzi: "北京", pinyin: "Běijīng", ru: "Пекин", lesson: 9 },
  { hanzi: "中国", pinyin: "Zhōngguó", ru: "Китай", lesson: 9 },
  { hanzi: "这里", pinyin: "zhèlǐ", ru: "здесь", lesson: 9 },
  { hanzi: "那里", pinyin: "nàlǐ", ru: "там", lesson: 9 },
  { hanzi: "哪里", pinyin: "nǎlǐ", ru: "где", lesson: 9 },

  // 10. Погода
  { hanzi: "天气", pinyin: "tiānqì", ru: "погода", lesson: 10 },
  { hanzi: "下雨", pinyin: "xiàyǔ", ru: "идёт дождь", lesson: 10 },
  { hanzi: "下雪", pinyin: "xiàxuě", ru: "идёт снег", lesson: 10 },
  { hanzi: "热", pinyin: "rè", ru: "жарко", lesson: 10 },
  { hanzi: "冷", pinyin: "lěng", ru: "холодно", lesson: 10 },
  { hanzi: "太阳", pinyin: "tàiyáng", ru: "солнце", lesson: 10 },
  { hanzi: "风", pinyin: "fēng", ru: "ветер", lesson: 10 },
  { hanzi: "云", pinyin: "yún", ru: "облако", lesson: 10 },

  // 11. Тело
  { hanzi: "头", pinyin: "tóu", ru: "голова", lesson: 11 },
  { hanzi: "手", pinyin: "shǒu", ru: "рука (кисть)", lesson: 11 },
  { hanzi: "脚", pinyin: "jiǎo", ru: "нога (стопа)", lesson: 11 },
  { hanzi: "眼睛", pinyin: "yǎnjing", ru: "глаза", lesson: 11 },
  { hanzi: "嘴", pinyin: "zuǐ", ru: "рот", lesson: 11 },
  { hanzi: "耳朵", pinyin: "ěrduo", ru: "уши", lesson: 11 },

  // 12. Одежда
  { hanzi: "衣服", pinyin: "yīfu", ru: "одежда", lesson: 12 },
  { hanzi: "裤子", pinyin: "kùzi", ru: "брюки", lesson: 12 },
  { hanzi: "鞋子", pinyin: "xiézi", ru: "обувь", lesson: 12 },
  { hanzi: "帽子", pinyin: "màozi", ru: "шапка", lesson: 12 },

  // 13. Животные
  { hanzi: "猫", pinyin: "māo", ru: "кошка", lesson: 13 },
  { hanzi: "狗", pinyin: "gǒu", ru: "собака", lesson: 13 },
  { hanzi: "鸟", pinyin: "niǎo", ru: "птица", lesson: 13 },
  { hanzi: "鱼", pinyin: "yú", ru: "рыба", lesson: 13 },
  { hanzi: "马", pinyin: "mǎ", ru: "лошадь", lesson: 13 },

  // 14. Профессии
  { hanzi: "老师", pinyin: "lǎoshī", ru: "учитель", lesson: 14 },
  { hanzi: "医生", pinyin: "yīshēng", ru: "врач", lesson: 14 },
  { hanzi: "学生", pinyin: "xuésheng", ru: "студент", lesson: 14 },
  { hanzi: "经理", pinyin: "jīnglǐ", ru: "менеджер", lesson: 14 },

  // 15. Качества
  { hanzi: "大", pinyin: "dà", ru: "большой", lesson: 15 },
  { hanzi: "小", pinyin: "xiǎo", ru: "маленький", lesson: 15 },
  { hanzi: "多", pinyin: "duō", ru: "много", lesson: 15 },
  { hanzi: "少", pinyin: "shǎo", ru: "мало", lesson: 15 },
  { hanzi: "高", pinyin: "gāo", ru: "высокий", lesson: 15 },
  { hanzi: "矮", pinyin: "ǎi", ru: "низкий (рост)", lesson: 15 },
  { hanzi: "新", pinyin: "xīn", ru: "новый", lesson: 15 },
  { hanzi: "旧", pinyin: "jiù", ru: "старый (вещь)", lesson: 15 },
  { hanzi: "漂亮", pinyin: "piàoliang", ru: "красивый", lesson: 15 },
  { hanzi: "忙", pinyin: "máng", ru: "занятой", lesson: 15 },

  // 16. Вопросы
  { hanzi: "什么", pinyin: "shénme", ru: "что", lesson: 16 },
  { hanzi: "为什么", pinyin: "wèishénme", ru: "почему", lesson: 16 },
  { hanzi: "怎么", pinyin: "zěnme", ru: "как", lesson: 16 },
  { hanzi: "多少", pinyin: "duōshao", ru: "сколько", lesson: 16 },
  { hanzi: "几", pinyin: "jǐ", ru: "сколько (малое число)", lesson: 16 },
  { hanzi: "吗", pinyin: "ma", ru: "вопросительная частица", lesson: 16 },
].map((w, i) => ({ id: i + 1, ...w }));

// Состав одиночных иероглифов: радикал/фонетик + короткая подсказка для запоминания.
// Исследования показывают, что разбор по компонентам заметно улучшает запоминание
// (например, все знаки с радикалом 水 «вода» легче учить вместе).
const RADICALS = {
  "请": { parts: "讠 + 青", note: "讠 «речь» + 青 (звуковая часть)" },
  "是": { parts: "日 + 疋", note: "日 «солнце» сверху" },
  "不": { parts: "一", note: "самостоятельный знак-отрицание" },
  "好": { parts: "女 + 子", note: "女 «женщина» + 子 «ребёнок» = хорошо" },
  "我": { parts: "戈", note: "радикал 戈 «копьё»" },
  "你": { parts: "亻 + 尔", note: "亻 «человек» + 尔 (звуковая часть)" },
  "他": { parts: "亻 + 也", note: "亻 «человек» + 也 (звуковая часть)" },
  "她": { parts: "女 + 也", note: "女 «женщина» + 也 (та же звуковая часть, что и у 他)" },
  "这": { parts: "辶 + 文", note: "辶 «движение/путь»" },
  "那": { parts: "⻏", note: "⻏ «место, город» справа" },
  "谁": { parts: "讠 + 隹", note: "讠 «речь» + 隹 «птица» (звуковая часть)" },
  "一": { parts: "一", note: "числительное, одна черта" },
  "二": { parts: "二", note: "числительное, две черты" },
  "三": { parts: "一", note: "числительное, три черты" },
  "四": { parts: "囗", note: "囗 «рамка/ограда» снаружи" },
  "五": { parts: "二", note: "древний знак пересечения" },
  "六": { parts: "八", note: "八 сверху «разделение»" },
  "七": { parts: "一", note: "числительное" },
  "八": { parts: "八", note: "радикал 八 «разделение», как две расходящиеся черты" },
  "九": { parts: "乙", note: "радикал 乙" },
  "十": { parts: "十", note: "числительное-крест" },
  "百": { parts: "一 + 白", note: "一 + 白 «белый» (звуковая часть)" },
  "零": { parts: "雨 + 令", note: "雨 «дождь» сверху + 令 (звуковая часть)" },
  "家": { parts: "宀 + 豕", note: "宀 «крыша» + 豕 «свинья» — свинья под крышей = дом" },
  "吃": { parts: "口 + 乞", note: "口 «рот» + 乞 (звуковая часть)" },
  "喝": { parts: "口 + 曷", note: "口 «рот» — им пьют" },
  "水": { parts: "水", note: "пиктограмма текущей воды" },
  "茶": { parts: "艹 + 木", note: "艹 «трава» + 木 «дерево»" },
  "菜": { parts: "艹 + 采", note: "艹 «трава» + 采 «собирать» — собранная зелень" },
  "年": { parts: "干", note: "пиктограмма урожая/года" },
  "月": { parts: "月", note: "пиктограмма луны/месяца" },
  "号": { parts: "口 + 丂", note: "口 «рот» сверху" },
  "点": { parts: "占 + 灬", note: "灬 «огонь» снизу (четыре точки)" },
  "去": { parts: "土 + 厶", note: "土 «земля» сверху" },
  "来": { parts: "木", note: "пиктограмма колоса пшеницы" },
  "看": { parts: "手 + 目", note: "手 «рука» над 目 «глаз» — рука козырьком, чтобы смотреть вдаль" },
  "听": { parts: "口 + 斤", note: "口 «рот» слева" },
  "说": { parts: "讠 + 兑", note: "讠 «речь» + 兑 (звуковая часть)" },
  "写": { parts: "冖", note: "冖 «крышка» сверху" },
  "读": { parts: "讠 + 卖", note: "讠 «речь» + 卖 (звуковая часть)" },
  "买": { parts: "大", note: "упрощённая форма" },
  "做": { parts: "亻 + 故", note: "亻 «человек» + 故 «причина, дело»" },
  "热": { parts: "埶 + 灬", note: "灬 «огонь» снизу — жар" },
  "冷": { parts: "冫 + 令", note: "冫 «лёд» (две точки) + 令 (звуковая часть)" },
  "风": { parts: "风", note: "упрощённая пиктограмма ветра" },
  "云": { parts: "二", note: "упрощённая форма (раньше писалось с 雨 «дождь» сверху)" },
  "头": { parts: "大", note: "упрощённая форма знака «голова» (радикал 页)" },
  "手": { parts: "手", note: "пиктограмма ладони с пальцами" },
  "脚": { parts: "月 + 却", note: "月 «тело/плоть» слева" },
  "嘴": { parts: "口 + 此 + 角", note: "口 «рот» слева" },
  "猫": { parts: "犭+ 苗", note: "犭 «зверь» + 苗 (звуковая часть)" },
  "狗": { parts: "犭 + 句", note: "犭 «зверь» + 句 (звуковая часть)" },
  "鸟": { parts: "鸟", note: "пиктограмма птицы" },
  "鱼": { parts: "鱼", note: "пиктограмма рыбы" },
  "马": { parts: "马", note: "пиктограмма лошади" },
  "大": { parts: "大", note: "пиктограмма человека с раскинутыми руками" },
  "小": { parts: "小", note: "три маленькие черты-точки" },
  "多": { parts: "夕 + 夕", note: "два знака 夕 «вечер» подряд = много" },
  "少": { parts: "小", note: "小 «маленький» с дополнительной чертой" },
  "高": { parts: "高", note: "пиктограмма высокой башни" },
  "矮": { parts: "矢 + 委", note: "矢 «стрела» слева" },
  "新": { parts: "亲 + 斤", note: "斤 «топор» справа" },
  "旧": { parts: "日", note: "日 сверху" },
  "忙": { parts: "忄 + 亡", note: "忄 «сердце» + 亡 — сердце вечно занято" },
  "几": { parts: "几", note: "пиктограмма маленького столика" },
  "吗": { parts: "口 + 马", note: "口 «рот» + 马 «лошадь» (звуковая часть) — частица вопроса" },
};

// Исходные тематические уроки — отдельная категория на главном экране.
LESSONS.forEach((l) => { l.category = "themes"; });
